apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
      - name: devops-backend
        image: christopherian2004/devops-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
